[package]
name = "brdgme-color"
version = "0.1.0"
authors = ["Michael Alexander <beefsack@gmail.com>"]

[dependencies]
brdgme-std = { git = "https://github.com/brdgme/std.git" }
regex = "*"
lazy_static = "*"
serde = "*"
serde_derive = "*"
