[package]
name = "brdgme-color"
version = "0.1.0"
authors = ["Michael Alexander <beefsack@gmail.com>"]

[dependencies]
brdgme-std = { path = "../std" }
regex = "*"
lazy_static = "*"
serde = "*"
serde_derive = "*"
