[package]
name = "brdgme-color"
version = "0.1.0"
authors = ["Michael Alexander <beefsack@gmail.com>"]

[dependencies]
regex = "1.0.5"
lazy_static = "0.2.6"
serde = "1.0.0"
serde_derive = "1.0.0"
failure = "0.1.1"